name: Insta Meal Bot

on:
    schedule:
    # 한국 시간(KST) 오후 10시에 매일 실행 (UTC 기준 13시)
    - cron: '0 13 * * *'
  workflow_dispatch: # 수동으로도 실행할 수 있게 하는 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install instagrapi

      - name: Run bot
        env:
          INSTA_ID: ${{ secrets.INSTA_ID }}
          INSTA_PW: ${{ secrets.INSTA_PW }}
        run: python main.py
