name: Insta Meal Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install instagrapi Pillow
          sudo apt-get -y install fonts-nanum

      - name: Run bot
        env:
          INSTA_ID: ${{ secrets.INSTA_ID }}
          INSTA_PW: ${{ secrets.INSTA_PW }}
        run: python main.py
